### ISSUE TITLE
setLoadChemCompInfo is not a method of the FileParsingParameters class on biojava versions 4.2.0, 4.2.9, 4.2.11

### ISSUE THREAD

**Issue by marceloqla** [biojava/biojava-tutorial#27]
On the link https://github.com/biojava/biojava-tutorial/blob/master/structure/chemcomp.md, we're told that we can fetch missing Chemical Component Definitions on the fly after setting params by using: "params.setLoadChemCompInfo(true);".

In BioJava versions: 4.2.0, 4.2.9 and 4.2.11, setLoadChemCompInfo is not a method of the FileParsingParameters class and therefore this solution is not valid.

**Comment by josemduarte** [comment]
Thanks for the report. Indeed that option was removed in 4.2.0. The default behaviour now is that the chemical component definitions are fetched on the fly. I'll update the documentation accordingly.

If you are interested in the details, see the original discussion in https://github.com/biojava/biojava/issues/313 and other linked issues there.

**Comment by josemduarte** [comment]
The docs are now updated, please let us know if there's any other issues.
